// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Alpha(Object<ffi::ClutterAlpha, ffi::ClutterAlphaClass, AlphaClass>);

    match fn {
        get_type => || ffi::clutter_alpha_get_type(),
    }
}

impl Alpha {}

pub const NONE_ALPHA: Option<&Alpha> = None;

impl fmt::Display for Alpha {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Alpha")
    }
}
