// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Animator(Object<ffi::ClutterAnimator, ffi::ClutterAnimatorClass, AnimatorClass>);

    match fn {
        get_type => || ffi::clutter_animator_get_type(),
    }
}

impl Animator {}

pub const NONE_ANIMATOR: Option<&Animator> = None;

impl fmt::Display for Animator {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Animator")
    }
}
