// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Animation(Object<ffi::ClutterAnimation, ffi::ClutterAnimationClass, AnimationClass>);

    match fn {
        get_type => || ffi::clutter_animation_get_type(),
    }
}

impl Animation {}

pub const NONE_ANIMATION: Option<&Animation> = None;

impl fmt::Display for Animation {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Animation")
    }
}
