// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;
use super::Behaviour;

glib_wrapper! {
    pub struct BehaviourDepth(Object<ffi::ClutterBehaviourDepth, ffi::ClutterBehaviourDepthClass, BehaviourDepthClass>) @extends Behaviour;

    match fn {
        get_type => || ffi::clutter_behaviour_depth_get_type(),
    }
}

impl BehaviourDepth {}

pub const NONE_BEHAVIOUR_DEPTH: Option<&BehaviourDepth> = None;

impl fmt::Display for BehaviourDepth {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "BehaviourDepth")
    }
}
