// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;
use crate::Behaviour;

glib_wrapper! {
    pub struct BehaviourOpacity(Object<ffi::ClutterBehaviourOpacity, ffi::ClutterBehaviourOpacityClass, BehaviourOpacityClass>) @extends Behaviour;

    match fn {
        get_type => || ffi::clutter_behaviour_opacity_get_type(),
    }
}

impl BehaviourOpacity {}

pub const NONE_BEHAVIOUR_OPACITY: Option<&BehaviourOpacity> = None;

impl fmt::Display for BehaviourOpacity {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "BehaviourOpacity")
    }
}
