// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Behaviour(Object<ffi::ClutterBehaviour, ffi::ClutterBehaviourClass, BehaviourClass>);

    match fn {
        get_type => || ffi::clutter_behaviour_get_type(),
    }
}

impl Behaviour {}

pub const NONE_BEHAVIOUR: Option<&Behaviour> = None;

impl fmt::Display for Behaviour {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Behaviour")
    }
}
