// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use super::BinAlignment;
use super::LayoutManager;
use ffi;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct BinLayout(Object<ffi::ClutterBinLayout, ffi::ClutterBinLayoutClass, BinLayoutClass>) @extends LayoutManager;

    match fn {
        get_type => || ffi::clutter_bin_layout_get_type(),
    }
}

impl BinLayout {
    pub fn new(x_align: BinAlignment, y_align: BinAlignment) -> BinLayout {
        assert_initialized_main_thread!();
        unsafe {
            LayoutManager::from_glib_none(ffi::clutter_bin_layout_new(
                x_align.to_glib(),
                y_align.to_glib(),
            ))
            .unsafe_cast()
        }
    }
}

pub const NONE_BIN_LAYOUT: Option<&BinLayout> = None;

impl fmt::Display for BinLayout {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "BinLayout")
    }
}
