// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use super::Actor;
use super::Animatable;
use super::Container;
use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Box(Object<ffi::ClutterBox, ffi::ClutterBoxClass, BoxClass>) @extends Actor, @implements Animatable, Container;

    match fn {
        get_type => || ffi::clutter_box_get_type(),
    }
}

impl Box {}

pub const NONE_BOX: Option<&Box> = None;

impl fmt::Display for Box {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Box")
    }
}
