// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;
use super::Color;
use super::PaintNode;
use super::PipelineNode;

glib_wrapper! {
    pub struct ColorNode(Object<ffi::ClutterColorNode, ffi::ClutterColorNodeClass, ColorNodeClass>) @extends PipelineNode, PaintNode;

    match fn {
        get_type => || ffi::clutter_color_node_get_type(),
    }
}

impl ColorNode {
    pub fn new(color: Option<&Color>) -> ColorNode {
        assert_initialized_main_thread!();
        unsafe {
            PaintNode::from_glib_full(ffi::clutter_color_node_new(color.to_glib_none().0))
                .unsafe_cast()
        }
    }
}

impl fmt::Display for ColorNode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ColorNode")
    }
}
