// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::object::Cast;
use glib::object::ObjectType as ObjectType_;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use super::ActorMeta;
use super::Color;
use super::Effect;
use super::OffscreenEffect;

glib_wrapper! {
    pub struct ColorizeEffect(Object<ffi::ClutterColorizeEffect, ffi::ClutterColorizeEffectClass, ColorizeEffectClass>) @extends OffscreenEffect, Effect, ActorMeta;

    match fn {
        get_type => || ffi::clutter_colorize_effect_get_type(),
    }
}

impl ColorizeEffect {
    pub fn new(tint: &Color) -> ColorizeEffect {
        assert_initialized_main_thread!();
        unsafe {
            Effect::from_glib_none(ffi::clutter_colorize_effect_new(
                tint.to_glib_none().0,
            ))
            .unsafe_cast()
        }
    }

    pub fn get_tint(&self) -> Color {
        unsafe {
            let mut tint = Color::uninitialized();
            ffi::clutter_colorize_effect_get_tint(
                self.to_glib_none().0,
                tint.to_glib_none_mut().0,
            );
            tint
        }
    }

    pub fn set_tint(&self, tint: &Color) {
        unsafe {
            ffi::clutter_colorize_effect_set_tint(
                self.to_glib_none().0,
                tint.to_glib_none().0,
            );
        }
    }

    pub fn connect_property_tint_notify<F: Fn(&ColorizeEffect) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_tint_trampoline<F: Fn(&ColorizeEffect) + 'static>(
            this: *mut ffi::ClutterColorizeEffect,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::tint\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_tint_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for ColorizeEffect {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ColorizeEffect")
    }
}
