// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;
use super::Actor;
use super::Animatable;
use super::Container;

glib_wrapper! {
    pub struct Group(Object<ffi::ClutterGroup, ffi::ClutterGroupClass, GroupClass>) @extends Actor, @implements Animatable, Container;

    match fn {
        get_type => || ffi::clutter_group_get_type(),
    }
}

impl Group {}

pub const NONE_GROUP: Option<&Group> = None;

impl fmt::Display for Group {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Group")
    }
}
