// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use super::Model;
use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct ListModel(Object<ffi::ClutterListModel, ffi::ClutterListModelClass, ListModelClass>) @extends Model;

    match fn {
        get_type => || ffi::clutter_list_model_get_type(),
    }
}

impl ListModel {}

pub const NONE_LIST_MODEL: Option<&ListModel> = None;

impl fmt::Display for ListModel {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ListModel")
    }
}
