// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Margin(Boxed<ffi::ClutterMargin>);

    match fn {
        copy => |ptr| ffi::clutter_margin_copy(mut_override(ptr)),
        free => |ptr| ffi::clutter_margin_free(ptr),
        get_type => || ffi::clutter_margin_get_type(),
    }
}

impl Margin {
    pub fn new() -> Margin {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::clutter_margin_new()) }
    }
}

impl Default for Margin {
    fn default() -> Self {
        Self::new()
    }
}
