// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use super::PaintNode;
use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct PipelineNode(Object<ffi::ClutterPipelineNode, ffi::ClutterPipelineNodeClass, PipelineNodeClass>) @extends PaintNode;

    match fn {
        get_type => || ffi::clutter_pipeline_node_get_type(),
    }
}

impl PipelineNode {}

pub const NONE_PIPELINE_NODE: Option<&PipelineNode> = None;

impl fmt::Display for PipelineNode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "PipelineNode")
    }
}
