// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Shader(Object<ffi::ClutterShader, ffi::ClutterShaderClass, ShaderClass>);

    match fn {
        get_type => || ffi::clutter_shader_get_type(),
    }
}

impl Shader {}

pub const NONE_SHADER: Option<&Shader> = None;

impl fmt::Display for Shader {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Shader")
    }
}
